name = "personal"
license = ""
licenselink = ""
description = ""
homepage = "https://github.com/danielmmetz/danielmmetz.github.io"
tags = []
features = []
min_version = "0.0.0"

[author]
  name = "Daniel Metz"
  homepage = "https://github.com/danielmmetz/danielmmetz.github.io"
